/** Machine-readable error codes returned in the `code` field of every error response. */
export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_PERMISSION: 'MISSING_PERMISSION',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];